ignore:
  - vulnerability: CVE-2026-33186 # libgrpc
  - vulnerability: CVE-2026-3805  # curl
  - vulnerability: CVE-2023-52356 # tiff
  - vulnerability: CVE-2026-4775  # tiff
  - vulnerability: CVE-2026-3805  # libcurl
  - vulnerability: CVE-2026-6732  # libxml2
  - vulnerability: CVE-2026-5773  # curl
  - vulnerability: CVE-2026-6276  # curl
  - vulnerability: CVE-2026-45447 # libcrypto3
  - vulnerability: CVE-2026-9076  # libcrypto3
  - vulnerability: CVE-2026-7383  # libcrypto3
  - vulnerability: CVE-2026-34180 # libcrypto3
  - vulnerability: CVE-2026-42764 # libcrypto3
  - vulnerability: CVE-2026-45445 # libcrypto3
  - vulnerability: CVE-2026-34183 # libcrypto3
  - vulnerability: CVE-2026-34182 # libcrypto3
  - vulnerability: CVE-2026-34181 # libcrypto3
  