packages:
  - "apps/messaging-api"
  - "apps/messaging-admin"
  - "apps/messaging-admin-next"
  - "apps/messaging"
  - "apps/messaging-support"
  - "apps/messaging-next"
  - "apps/citizen-portal"
  - "packages/authorisation"
  - "packages/citizen-shared"
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@ogcio/*"
